const R = '/Users/nathantaichman/The Studio/Projects/Project Pommora/Core'
const { rewriteConnections, rewriteHeadingConnections, rewriteFrontmatterConnections } = await import(R + '/Connections/rewrite')
const { readLink, linkValueFromEdit, linkEditText, linkDisplayText, wholeValueLink } = await import(R + '/Connections/linkValue')
const { linksIn, frontmatterMentions, valueLinks } = await import(R + '/Connections/scan')
const { parseConnectionText } = await import(R + '/Connections/connections')
const J = (x: unknown) => JSON.stringify(x)
const vals = ['[[Old]]', '[[Old|a]]', '[[Old|New]]', '[[Old#H]]', '[[Old#H|a]]', '[x](Old)', '[x](Old#H)', '[[#H]]', '[[#H|a]]', '[x](#H)', '[[ Old ]]', '[x](https://old.com)', 'see [[Old]] too', '[New](Old)']
console.log('--- title rename Old->New: body-path | frontmatter-path')
for (const v of vals) console.log(J(v), '=>', J(rewriteConnections(v, 'Old', 'New')), '|', J(rewriteFrontmatterConnections({ k: v }, 'Old', { title: 'New' }).k ?? v))
console.log('--- own-page title rename (own=Own) Own->Neu, value [[#H]]')
console.log(J(rewriteConnections('[[#H]]', 'Own', 'Neu')), J(rewriteFrontmatterConnections({ k: '[[#H]]' }, 'Own', { title: 'Neu' }, 'Own')))
console.log('--- heading rename Old#H -> H2 (own=Old): body | fm')
for (const v of ['[[Old#H]]', '[[Old#H|a]]', '[x](Old#H)', '[[#H]]', '[x](#H)', '§H', '[[Old#H|H2]]'])
  console.log(J(v), '=>', J(rewriteHeadingConnections(v, 'Old', 'H', 'H2', 'Old', ['H'])), '|', J(rewriteFrontmatterConnections({ k: v }, 'Old', { heading: 'H', to: 'H2' }, 'Old').k ?? v))
console.log('--- heading rename to inexpressible "A|B": body | fm')
for (const v of ['[[Old#H]]', '[x](Old#H)']) console.log(J(v), J(rewriteHeadingConnections(v, 'Old', 'H', 'A|B', 'Old')), J(rewriteFrontmatterConnections({ k: v }, 'Old', { heading: 'H', to: 'A|B' }, 'Old').k ?? v))
console.log('--- readLink kinds')
for (const v of vals) console.log(J(v), J(readLink(v)))
console.log('--- index: frontmatterMentions + valueLinks per value (own=Me)')
for (const v of vals) console.log(J(v), J(frontmatterMentions({ k: v }, 'Me')), J([...valueLinks({ k: v }, 'Me')].map((h) => [h.syntax, h.target, h.qualifier])))
const resolve = (t: string) => (['old', 'page', 'dup'].includes(t.toLowerCase()) ? (t[0].toUpperCase() + t.slice(1)) : null)
console.log('--- linkValueFromEdit (resolver knows Old, Page)')
for (const v of ['[[Old]]', '[[Old|a]]', '[x](Old)', '[x](Old#H)', '[x](https://a.com)', '[x](example.com)', 'example.com', '[[#H]]', '[[Nope]]', '[x](Nope)', '[x](#H)', '[[Old#H|a]]', '[a](b) [c](d)', '[^1](https://a.com)', '[[Old|Old]]'])
  console.log(J(v), '=>', J(linkValueFromEdit(v, undefined, resolve)))
console.log('--- linkEditText / linkDisplayText')
for (const v of ['[[Old|a]]', '[x](Old)', '[x](https://a.com)', '[[#H]]', '[[Old#H]]']) console.log(J(v), J(linkEditText(v)), J(linkDisplayText(v)))
console.log('--- yaml nested', J(wholeValueLink([['Old']])), J(parseConnectionText('[[#H]]')))
