// Writes Symbols/iconNames.ts from the full Lucide set; run `npm run icons:names` after a lucide-react bump.
import { writeFileSync } from 'node:fs'
import { ALL_ICONS } from '../Symbols/allSymbols.ts'

const HEADER = `// GENERATED by \`npm run icons:names\` (UIX/scripts/iconNames.mjs) — the eager kebab-id roster of the full Lucide set, strings only, no glyph components.
// It carries no glyph imports, so it stays in the main bundle while the glyph set (allSymbols) loads on demand.
`

const body = ALL_ICONS.map((e) => `  '${e.id}',`).join('\n')
writeFileSync(
  new URL('../Symbols/iconNames.ts', import.meta.url),
  `${HEADER}export const ICON_NAMES: ReadonlySet<string> = new Set([\n${body}\n])\n`,
)
