// Writes Symbols/iconNames.ts and Symbols/iconTags.ts from the full Lucide set; run `npm run icons:names` after a lucide-react bump, with lucide-static pinned to the same version.
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { ALL_ICONS } from '../Symbols/iconRoster.ts'

const NAMES_HEADER = `// GENERATED by \`npm run icons:names\` (UIX/scripts/iconNames.mjs) — the eager kebab-id roster of the full Lucide set, strings only, no glyph components.
// It carries no glyph imports, so it stays in the main bundle while the glyph set (allSymbols) loads on demand.
`

const TAGS_HEADER = `// GENERATED by \`npm run icons:names\` (UIX/scripts/iconNames.mjs) from lucide-static's tags.json — each icon's Lucide search tags, keyed by its kebab id.
`

const names = ALL_ICONS.map((e) => `  '${e.id}',`).join('\n')
writeFileSync(
  new URL('../Symbols/iconNames.ts', import.meta.url),
  `${NAMES_HEADER}export const ICON_NAMES: ReadonlySet<string> = new Set([\n${names}\n])\n`,
)

// Lucide's canonical names split digits differently from lucide-react's export names (`arrow-down-0-1` against `ArrowDown01`), so the two meet dashless.
const dashless = (id) => id.replace(/-/g, '')
const require = createRequire(import.meta.url)
const lucideTags = require('lucide-static/tags.json')
const byDashless = new Map(Object.entries(lucideTags).map(([name, tags]) => [dashless(name), tags]))

const tags = ALL_ICONS.map((e) => {
  const entry = byDashless.get(dashless(e.id))
  if (!entry)
    throw new Error(`lucide-static has no tags for '${e.id}' — pin it to lucide-react's version`)
  return `  ${JSON.stringify(e.id)}: ${JSON.stringify(entry)},`
}).join('\n')
const tagsFile = fileURLToPath(new URL('../Symbols/iconTags.ts', import.meta.url))
writeFileSync(
  tagsFile,
  `${TAGS_HEADER}export const ICON_TAGS: Readonly<Record<string, readonly string[]>> = {\n${tags}\n}\n`,
)
execFileSync(
  process.execPath,
  [require.resolve('@biomejs/biome/bin/biome'), 'format', '--write', tagsFile],
  {
    stdio: 'inherit',
  },
)
